### ISSUE TITLE
Hi，How to specify the encoding type? eg:gb2312

### ISSUE THREAD

**Issue by CatcherX** [joelverhagen/AngleSharp.NetHttp#2]
https://github.com/joelverhagen/AngleSharp.NetHttp/blob/0599a5b331e444a5b6fe4319c25ec9791f7f6fcc/AngleSharp.NetHttp.Sandbox/Program.cs#L28

or how to parse sting to document?

**Comment by joelverhagen** [comment]
Duplicate of https://github.com/joelverhagen/AngleSharp.NetHttp/issues/1.
